export const dummyMediaItems = [
  {
    pk: 1,
    title: '인터스텔라',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    genres: ['SF', '드라마'],
    releaseDate: '2014-11-06',
    runtime: '2h 49m',
    overview: '지구의 생존이 위태로워진 미래, NASA의 파일럿 쿠퍼는 우주를 탐사하며 인류의 미래를 찾아 나선다.',
    keywords: ['space', 'black hole', 'love', 'time dilation'],
    reviewScore: 94,
    similarityScore: 91,
    director: '크리스토퍼 놀란',
    cast: ['매튜 맥커너히', '앤 해서웨이', '제시카 차스테인'],
  },
  {
    pk: 2,
    title: '인셉션',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    genres: ['SF', '스릴러'],
    releaseDate: '2010-07-21',
    runtime: '2h 28m',
    overview: "꿈속에서 꿈을 꾸는 '인셉션'을 통해 상대의 무의식에 아이디어를 심는 미션을 수행하는 도미닉.",
    keywords: ['dream', 'subconscious', 'heist', 'limbo'],
    reviewScore: 92,
    similarityScore: 89,
    director: '크리스토퍼 놀란',
    cast: ['레오나르도 디카프리오', '조셉 고든 레빗', '엘렌 페이지'],
  },
  {
    pk: 3,
    title: '파묘',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    genres: ['공포', '미스터리'],
    releaseDate: '2024-03-07',
    runtime: '1h 41m',
    overview: '불길한 기운이 감도는 묘를 이장하면서 벌어지는 초자연적 사건들. 장례지도사와 무속인이 진실에 다가간다.',
    keywords: ['grave', 'curse', 'shaman', 'ritual'],
    reviewScore: 83,
    similarityScore: 86,
    director: '장재현',
    cast: ['최민식', '김고은', '이도현'],
  },
  {
    pk: 4,
    title: '라라랜드',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    genres: ['로맨스', '뮤지컬'],
    releaseDate: '2016-12-07',
    runtime: '2h 8m',
    overview: '꿈을 좇는 두 남녀의 사랑과 이별, 그리고 그 속에서 피어나는 음악과 삶의 의미.',
    keywords: ['jazz', 'dream', 'love', 'musician'],
    reviewScore: 91,
    similarityScore: 87,
    director: '데이미언 셔젤',
    cast: ['라이언 고슬링', '엠마 스톤'],
  },
  {
    pk: 5,
    title: '기생충',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    genres: ['드라마', '스릴러'],
    releaseDate: '2019-05-30',
    runtime: '2h 12m',
    overview: '서로 다른 두 가족의 만남으로 벌어지는 예측 불가의 블랙코미디. 빈부격차와 계급 갈등을 다룬 수작.',
    keywords: ['poverty', 'class', 'deception', 'family'],
    reviewScore: 96,
    similarityScore: 90,
    director: '봉준호',
    cast: ['송강호', '이선균', '조여정'],
  },
  {
    pk: 6,
    title: '조커',
    posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    genres: ['범죄', '드라마', '스릴러'],
    releaseDate: '2019-10-02',
    runtime: '2h 2m',
    overview: '고통받는 코미디언 아서 플렉이 점차 광기에 빠져들며 조커로 변해가는 과정을 그린 영화.',
    keywords: ['madness', 'society', 'violence', 'origin story'],
    reviewScore: 88,
    similarityScore: 85,
    director: '토드 필립스',
    cast: ['호아킨 피닉스', '로버트 드 니로'],
  },
  {
    pk: 7,
    title: '이터널스',
    posterUrl: 'https://image.tmdb.org/t/p/w500/b6qUu00iIIkXX13szFy7d0CyNcg.jpg',
    genres: ['액션', 'SF'],
    releaseDate: '2021-11-03',
    runtime: '2h 37m',
    overview: '수천 년간 지구를 지켜온 불사의 종족 이터널스가 인류의 새로운 위협 앞에 다시 모인다.',
    keywords: ['immortality', 'celestial', 'superhero', 'marvel'],
    reviewScore: 67,
    similarityScore: 70,
    director: '클로이 자오',
    cast: ['젬마 찬', '리차드 매든', '안젤리나 졸리'],
  },
  {
    pk: 8,
    title: '아바타: 물의 길',
    posterUrl: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    genres: ['SF', '모험'],
    releaseDate: '2022-12-14',
    runtime: '3h 12m',
    overview: '판도라 행성에서의 새로운 위협에 맞서 제이크 설리 가족이 물의 부족과 연합해 싸운다.',
    keywords: ['avatar', 'ocean', 'family', 'rebellion'],
    reviewScore: 82,
    similarityScore: 84,
    director: '제임스 카메론',
    cast: ['샘 워딩턴', '조 샐다나', '시고니 위버'],
  },
  {
    pk: 9,
    title: '어벤져스: 엔드게임',
    posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    genres: ['액션', '모험', 'SF'],
    releaseDate: '2019-04-24',
    runtime: '3h 1m',
    overview: '타노스에 의해 절반이 사라진 세상. 살아남은 어벤져스가 이를 되돌리기 위해 마지막 전투를 벌인다.',
    keywords: ['time travel', 'hero', 'sacrifice', 'team'],
    reviewScore: 94,
    similarityScore: 88,
    director: '안소니 루소, 조 루소',
    cast: ['로버트 다우니 주니어', '크리스 에반스', '스칼렛 요한슨'],
  },
  {
    pk: 10,
    title: '해리 포터와 마법사의 돌',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    genres: ['판타지', '모험'],
    releaseDate: '2001-12-14',
    runtime: '2h 32m',
    overview: '11살 생일에 호그와트 마법학교에 입학하게 된 해리 포터의 마법 세계 입문기.',
    keywords: ['wizard', 'magic', 'school', 'friendship'],
    reviewScore: 87,
    similarityScore: 90,
    director: '크리스 콜럼버스',
    cast: ['다니엘 래드클리프', '루퍼트 그린트', '엠마 왓슨'],
  }
];